#!/bin/bash

if [ $# -ne 1 ]; then
    echo -e "\t[error] usage: ./populate [problemfolder]"
    exit 1
fi

problem_folder="$1"
[[ "${problem_folder}" != */ ]] && problem_folder="${problem_folder}/"

problems_to_add=(
    "0704_binary-search"
    "0074_search-a-2D-matrix"
    "0875_koko-eating-bananas"
    "0153_find-minimum-in-rotated-sorted-array"
    "0033_search-in-rotated-sorted-array"
    "0981_time-based-key-value-store"
    "0004_median-of-two-sorted-arrays"
)

if [ ! -x "./new" ]; then
    echo -e "[error] './new' script not found or not executable"
    exit 1
fi

for problem in "${problems_to_add[@]}"; do
    ./new "${problem_folder}${problem}"
done
