#!/bin/bash

if [ $# -ne 1 ]; then
    echo -e "\t[error] usage: ./populate [problemfolder]"
    exit 1
fi

problem_folder="$1"
[[ "${problem_folder}" != */ ]] && problem_folder="${problem_folder}/"

problems_to_add=(
    "0121_best-time-to-buy-and-sell-stock"
    "0003_longest-substring-without-repeating-characters"
    "0424_longest-repeating-character-replacement"
    "0567_permutation-in-string"
    "0076_minimum-window-substring"
    "0239_sliding-window-maximum"
)

if [ ! -x "./new" ]; then
    echo -e "\t[error] './new' script not found or not executable"
    exit 1
fi

for problem in "${problems_to_add[@]}"; do
    ./new "${problem_folder}${problem}"
done
